on:
  push:
    branches: [ master ]

name: AzureMLOpsTrain

jobs:
  setup-aml-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout MLOps Repository
      id: checkout_repository
      uses: actions/checkout@v2

    - name: Login with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        allow-no-subscriptions: true

    - name: Azure CLI script - Prepare and run PyTorch  Training on Azure ML
      uses: azure/CLI@v1
      with:
        azcliversion: 2.43.0
        inlineScript: |
          az extension add -n ml
          cd MLOps
          echo $RESOURCE_GROUP
          az ml job create train.yml --subscription '${{ secrets.AZURE_SUBSCRIPTION }}' --resource-group '${{ secrets.RESOURCE_GROUP }}' --workspace-name '${{ secrets.AML_WORKSPACE }}'